name: Display Introduction

on:
  schedule: # Run workflow automatically
    - cron: '0 * * * *' # Runs every hour, on the hour
  workflow_dispatch: # Run workflow manually (without waiting for the cron to be called), through the GitHub Actions Workflow page directly

jobs:
  display-introduction:
    runs-on: ubuntu-latest
    steps:
      - name: Display Introduction
        uses: lowlighter/metrics@latest
        with:
          filename: assets/introduction.svg
          token: ${{ secrets.TOKEN }}
          plugin_introduction: true

